#!/bin/bash

# This sets up the class paths
source ~/.bashrc_custom

PWD=`pwd`
GIT=/home/barb/Working/Git
DATA=/home/barb/Working/Data

TYPE=JobBoards
JOB_BOARDS_OUTPUT=${DATA}/${TYPE}
DATE=$(date +"%b%d")
STATS=${DATA}/Statistics/${DATE}

mkdir $STATS

for domain in linkedin careers livecareer blockchain-com indeed cryptojobs blocktribe monster dice google angel cryptcareers; do

    # This will do the actual crawling...
    ./Specific/run_$domain.sh

done

cd $JOB_BOARDS_OUTPUT
for domain in *; do
  
   SPECIFIC_OUTPUT=${JOB_BOARDS_OUTPUT}/$domain

   # Now Post Process...This runs across the basic crawled 
   # data and produces some extra fields, like matching terms on skills
   for f in ${SPECIFIC_OUTPUT}/*_; do

      # The crawled output is the initial "index" data.  This data will 
      # get added to as the steps below are executed.
      cp $f $f"index"

      # Process over the crawled data and generate some extra index fields 
      java -jar $GIT/PostProcess/target/bbt-post-process-1.0.0-SNAPSHOT.jar CrawledData $f 

      # Add the extra fields that got generated by the process above to the 
      # basic index fields that we stared with.
      java -jar $GIT/PostProcess/target/bbt-post-process-1.0.0-SNAPSHOT.jar UpdateIndex $f"index" $f"basic_extra_fields" 

   done

   # Compute Stats
   # This is going to put 2 stats files in the SPECIFIC_OUTPUT directory
   java -jar $GIT/PostProcess/target/bbt-post-process-1.0.0-SNAPSHOT.jar ComputeStats $SPECIFIC_OUTPUT

   for s in ${SPECIFIC_OUTPUT}/stats*; do
       just_file=$(basename $s)
       echo "filename ... $just_file ;  domain ... $domain  ; destination  $STATS/${domain}-${just_file} "
       cp $s $STATS/${domain}-${just_file}
   done
done

# Compute Overall Statistics.
JAR=$GIT/PostProcess/target/bbt-post-process-1.0.0-SNAPSHOT.jar
java -jar $JAR AggragateStats ~/Working/Data/Statistics/${DATE} keyterms 
java -jar $JAR AggragateStats ~/Working/Data/Statistics/${DATE} phrases-1
java -jar $JAR AggragateStats ~/Working/Data/Statistics/${DATE} phrases-2
java -jar $JAR AggragateStats ~/Working/Data/Statistics/${DATE} phrases-3

