#!/bin/bash

JAR=/home/barb/Working/Git/Crawler4J/target/bbt-crawler4j-1.0.0-SNAPSHOT.jar
CRAWL_CONFIG=/home/barb/Working/Git/Scripts/config.txt
LOGGING_CONFIG=-Djava.util.logging.config.file=/home/barb/Working/Git/Scripts/logger.txt

java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://ixo.foundation/
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://kryptoseoul.com/
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://lpdwww.epfl.ch/
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://zondax.ch/
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG https://agoric.com/
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG https://airgap.it/
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG https://althea.org/
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG https://cosmos.network/
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG https://gitcoin.co/
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG https://github.com/
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG https://hubble.figment.network/
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG https://interchain.io/
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG https://kadena.io/
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG https://lunamint.com/
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG https://lunie.io/
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG https://nomic.io/
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG https://summa.one/
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG https://tendermint.com/
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG https://tonyarcieri.com/
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG https://www.forbole.com/
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG https://www.fullnode.berlin/
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG https://www.inf.usi.ch/
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG https://www.irisnet.org/
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG https://www.openmoneyinitiative.org/
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG https://www.proofofstakealliance.org/
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG https://www.regen.network/
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG https://www.she256.org/
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG https://www.swishlabs.com/
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG https://coloradoblockchain.com/companies 
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG https://www.sbir.gov/sbirsearch/topic/current/Blockchain
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://blockdaemon.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://blocklancer.net
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://blockmint.ai
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://blockpit.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://blocksmith.tech
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://blockvigil.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://bloom.co
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://bloq.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://bloqs4.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://bron.tech
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://bulvrdapp.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://bumo.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://bundle.network
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://bundlefi.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://byzgen.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://bzx.network
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://cakedefi.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://capitaldigi.info
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://carnesvalidadas.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://casky.io/uk
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://cerealia.ch
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://chaindesk.cn
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://chainplus.one
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://chainvu.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://chatex.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://chekk.me
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://chromia.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://clockworktrading.net
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://cmorq.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://coalpha.ai
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://coinbundle.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://coincheckup.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://coindcx.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://coindust.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://coinected.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://coinlend.org
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://coinmeet.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://coinmetrics.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://cointracker.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://coinve.st
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://commoninterest.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://consiliumcrypto.ai
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://covee.network
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://coverhero.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://credify.one
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://credmark.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://creosafe.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://criptalia.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://cruzeo.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://crypticlegends.co
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://crypto.tickets
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://cryptocashout.net
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://cryptowerk.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://ctrlshift.co
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://curioinvest.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://custostech.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://cygnetise.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://daohub.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://daostack.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://dappradar.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://darwinlabs.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://datasl.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://datavest.org
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://debune.org
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://decadent.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://decent.ch
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://definer.org
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://dexfreight.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://dimuto.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://dmgblockchain.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://donut.app
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://dora.network
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://droneenergy.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://dstoq.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://dtco.co
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://durachain.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://dyne.network
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://e11.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://earnly.cash
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://editional.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://eevet.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://eirium.tech
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://elemential.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://elementus.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://elixxir.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://elkrem.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://emphy.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://energyweb.org
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://enigio.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://eontoken.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://equallyt.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://equipmentconnect.co.uk
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://eristica.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://ethichub.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://evenfound.org
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://evercoin.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://everitoken.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://evernym.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://everprove.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://eversend.co
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://everythink.ai
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://expocore.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://figment.network
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://finboot.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://findable.net
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://finexity.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://flipsidecrypto.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://fluence.network
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://fluence.sh
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://flur.ee
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://flux.market
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://fortmatic.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://freebitcoins.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://fresco.work
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://funtrench.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://futureorion.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://gamerammo.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://gembex.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://geodb.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://geon.network
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://geoprotocol.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://get-hey.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://getloops.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://getportal.co
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://getty.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://gilded.finance
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://ginco.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://gizer.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://gjain.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://globatalent.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://globula.space
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://godcoin.gold
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://groundhog.network
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://grove.works
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://gundb.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://harenadata.net
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://hathor.network
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://helix.works
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://heraspace.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://hetchr.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://heypiggybank.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://highcastle.co
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://hihiwallet.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://hijro.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://home.ribon.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://homebloc.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://horizenlabs.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://horizongames.net
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://hu-manity.co
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://hummingbot.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://hyperlinq.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://iame.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://ico.ipstock.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://icon.foundation/en
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://icowatchdog.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://icoxinnovations.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://inplaza.co
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://insinoventures.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://inspecto.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://instadapp.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://insurevite.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://internxt.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://interstellar.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://inviou.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://inwara.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://iotblock.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://iotw.cloud
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://isun.one
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://ixo.foundation
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://jaak.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://jawanashop.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://jeench.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://kabn.network
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://kenetic.capital
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://kepler.network
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://keyrock.eu
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://knowrx.mobi
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://kodebox.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://koinearth.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://koinex.in
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://kolokium.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://kratosinnovationlabs.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://kronoverse.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://kubemake.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://kudigo.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://kzencorp.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://lbry.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://leadbestconsultant.com/en
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://lendflo.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://lendonomy.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://liancaijing.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://lifeid.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://ligero-inc.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://linen.app
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://lino.network
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://liqease.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://lisk.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://logisee.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://logosblock.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://lumachain.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://lunardigitalassets.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://lurkin.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://luxtag.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://lyfegen.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://madnetwork.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://maicapital.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://makersplace.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://mankindgames.net
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://mannarobotics.ai
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://matter-labs.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://medibloc.org/en
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://meeco.me
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://membersheep.net
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://messbusters.co
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://milin.searchain.net
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://mintdice.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://moeco.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://monax.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://monerium.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://moonblock.ai
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://multiledgers.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://must.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://mvs.org
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://nayuta.co
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://nebulas.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://netvote.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://neukind.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://newbanking.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://news.one
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://nimiq.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://ninjapromo.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://nuid.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://nymtech.net
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://oin.space
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://omnibloc.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://omniex.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://omnitude.tech
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://opensea.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://optherium.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://orderbook.net
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://originalmy.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://orvium.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://otdocs.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://pacific.org
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://parachute8.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://paritytech.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://path.net
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://paymentbox.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://payninja.co
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://paysic.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://peerledger.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://petrochain.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://photocert.co.uk
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://pixura.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://plasmapay.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://points.org
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://portfolio.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://portion.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://portis.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://poseidon.network
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://prasaga.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://predictev.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://presale.dolphin.bi
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://procivis.ch
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://procurean.network
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://propertytrees.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://pwnny.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://quid.li
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://quid.works
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://ramp.network
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://realblocks.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://realtybits.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://redcab.co
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://request.network
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://resonancex.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://review.network
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://ricex.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://rise.vision
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://rucove.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://rulisting.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://seafico.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://securitytokengroup.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://seed
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://settlemint.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://shiftcrypto.ch
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://shivom.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://sia.tech
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://simmst.de
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://skuchain.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://skux.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://smartcapitalx.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://solana.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://solarsitedesign.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://solaster.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://solvent.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://sorare.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://sot.one
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://spatium.net
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://spectrocoin.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://spl.yt
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://splash.tech
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://stakewith.us
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://stampery.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://stardust.gg
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://startupwharf.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://steamchain.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://stokr.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://strixleviathan.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://strongblock.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://suavei.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://superblocks.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://swazm.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://syncfab.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://synq.tech
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://taikai.network
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://talao.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://tangany.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://tartle.co
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://tauros.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://taxa.network
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://teamkraft.net
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://teex.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://tellspec.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://tesseract.one
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://thebhub.co.ke
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://thecargocoin.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://thelabz.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://themonetizr.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://thenemesis.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://thinkhrx.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://thoughtriver.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://tictalk.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://timeus.org
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://titanseal.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://tixguru.co
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://tokengazer.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://tokengroup.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://tokeniq.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://tokenonly.cn
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://topos.network
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://traderbox.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://transitnet.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://transmute.industries
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://transship.net
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://trato.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://trmlabs.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://trustabit.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://trustlesslab.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://trustverse.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://tunnel.money
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://tuoluocaijing.cn
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://tycho-solutions.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://ubapesa.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://ubby.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://ucrowdme.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://unblockanalysis.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://uniquid.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://unitedcrowd.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://unl.global
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://unlock-protocol.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://upland.me
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://vaultwallet.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://vega.xyz
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://veil.co
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://ventureum.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://veriledger.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://vetty.co
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://vincoin.cash
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://vipicash.no
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://vopay.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://vrallart.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://vrexlab.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://wallid.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://walnut.exchange
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://wanchain.org
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://we-trade.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://welove.education
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://whalelend.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://willems.ventures
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://wireline.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://withsempo.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://wr.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.1mpactrevolution.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.22xfund.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.2525.ventures
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.a-malgam.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.aballoon.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.aclaro.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.adelphoi.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.aegiscustody.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.aggregion.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.agora-innovation.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.aidos.nyc
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.alphaswap.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.amberdata.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.aminopay.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.anchain.ai
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.anchorusd.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.ant-invest.info
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.anyblockanalytics.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.apio.tech
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.apla.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.appcitylife.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.appii.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.appsco.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.arabianchain.org/index.php/en
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.arexre.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.argent.xyz
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.artchain.world
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.arweave.org
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.atlascity.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.avansa.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.avenews-gt.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.azaadhealth.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.aztecprotocol.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.b91.com/en/recruit
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.babelbank.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.baoquan.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.beautypark.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.bernstein.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.bfx.nu
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.bigcontrols.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.bitbutter.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.bitcliq.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.bitfair.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.bitkub.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.bitmama.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.bitnexo.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.bitofproperty.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.bitpremier.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.bitsimple.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.bitwiseinvestments.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.bizhihui.vip
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.blackbird.ai
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.blockchain-studio.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.blockchaincompany.info
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.blockchaindev.eu
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.blockchainlock.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.blockchyp.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.blockclaim.ai
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.blockcrowd.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.blockide.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.blockparty.org
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.blocksource.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.blockstate.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.blockstein.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.blockven.co
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.blocwatch.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.blok-z.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.blokur.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.bocheninc.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.bombaysour.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.bosonprotocol.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.bredtoken.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.brickfunding.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.bridgez.co
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.bthub.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.bugx.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.catallact.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.cbnt.io/index-en.html
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.cdtrust.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.celer.network
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.centre.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.cere.network
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.chaindigg.cn
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.chaingotech.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.chainhoo.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.chainnews.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.chainup.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.civic.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.cloud-africa.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.cloudintechnologies.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.coin.space
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.coinbask.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.coinblok.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.coincorner.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.coindirect.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.coingenius.ai
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.coinplus.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.commercialpassport.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.conflux-chain.org
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.consilx.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.cosmicinfoventures.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.coverus.health
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.crayonic.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.crazeshine.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.cronj.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.cryptomkt.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.cryptopets.co
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.cryptyk.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.curisium.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.curv.co
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.cystellar.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.dacebook-blockchain.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.dapp.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.dappp.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.datablock.one
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.dealerbag.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.deskviz.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.dextf.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.dfuse.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.digital-startup.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.dioreum.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.diyblockchain.co
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.dnatix.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.docademic.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.dominode.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.ecomchain.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.ecosteer.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.electivegroup.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.elementzero.network
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.elemetric.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.elevatyr.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.elyps.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.empower.eco
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.emx.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.encrypgen.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.energyfunders.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.epiphyte.us
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.etoshi.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.exoblock.net
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.fastwin.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.ficustrading.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.finboard.pro
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.finfabrik.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.finnoq.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.finteractions.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.fission.org
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.fluida.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.fluidity.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.fluxiot.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.foam.space
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.fota.top
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.foxbit.com.br
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.freeverse.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.freightbro.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.fshchain.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.fusechain.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.fxclr.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.gamedex.co
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.gamerhash.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.geegee.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.gigtricks.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.gk8.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.globacap.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.globedx.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.gowithmi.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.gref.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.gunclear.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.halosinsurance.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.hashdex.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.helixcard.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.herdius.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.herosphere.gg
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.hiredblock.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.honeycomb-colony.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.hoopoun.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.hoopox.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.huckadventures.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.hull-coin.org
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.hun.it
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.hydrogenplatform.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.hyperbidder.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.i2chain.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.ichain.co.jp/index_en.html
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.iconicchain.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.iconium.it
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.icosaving.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.idf3.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.illamed.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.inari.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.incuto.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.independentreserve.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.inkrypt.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.innodt.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.invault.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.investacrowd.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.isa-systems.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.ixledger.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.johnwick.io/en.html
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.jointer.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.katalysis.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.kepp.com.my
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.knowmenow.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.kognition.ai
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.kork.app
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.korrobox.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.kover.ai
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.learningmachine.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.ledgie.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.leondrino.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.lianantech.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.liquefy.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.liquidata.co
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.lisainsurtech.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.lition.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.livarava.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.lumit.mx
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.lunarcrush.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.luthersystems.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.lzine.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.marlin.pro
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.matchplace.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.materials.zone
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.mattereum.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.mdw.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.menapay.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.merit.me
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.merklescience.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.metalpay.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.mezzofy.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.minecraft-fitness.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.mineful.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.minka.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.monart.art
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.moneymatch.app
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.moovaz.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.morfin.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.morpher.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.motionwerk.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.mtv.ac
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.mwtech.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.mxc.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.mynextmatch.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.mystreamtechnologies.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.nexusmutual.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.nia-technologies.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.nickel.to
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.nineseals.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.nodecapital.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.nodeventure.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.norbloc.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.novamining.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.nxmlabs.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.obsidians.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.ockam.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.ocyan.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.odaily.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.okniex.me
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.oncochain.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.openavn.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.openhealth.cc
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.openledger.info
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.opennity.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.operem.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.orachain.top
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.originprotocol.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.oveit.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.ovex.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.oxio.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.panacea.ag
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.paperchain.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.pathfynders.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.payflip.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.paywithgrey.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.pedalapp.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.peermountain.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.peoplesculture.co
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.percipientcx.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.playvici.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.pocketh.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.poleecy.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.popvue.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.prifina.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.privatemarket.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.projectfred.co
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.prometheum.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.proof.work
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.proovstation.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.propineglobal.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.pynk.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.q2igroup.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.qbrics.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.qlikchain.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.quidax.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.quotfy.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.radpay.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.reengen.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.risepu.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.roundleague.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.routeique.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.rtechgroup.net
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.rubinway.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.rxall.net
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.sabr.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.safechain.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.sagewise.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.satoshi.ltd
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.savvy.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.scroll.network
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.seafoodsouq.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.securemarking.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.selfplatform.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.sendfriend.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.sevaexchange.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.shano.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.shrimpy.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.silkchain.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.simbachain.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.simplyvitalhealth.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.skeps.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.skew.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.skymavis.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.slingr.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.smartaxiom.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.sncrating.com/en
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.snowball.money
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.socialpay.me
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.soliduslabs.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.solvewithvia.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.sparrowexchange.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.spartera.network
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.spider.store
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.spot-bitcoin.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.starkdrones.org
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.stars-mine.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.statwig.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.steelbutsmart.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.stemapp.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.stopfakefood.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.streetcred.co
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.strongsalt.com/index.html
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.supa.ai
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.sweetbridge.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.swissrealcoin.ch
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.swyfthomes.co
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.tantu.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.tassat.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.taurenmedia.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.the-gatsby.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.theblockcrypto.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.thesmbx.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.thiswayglobal.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.tienchat.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.tienpay.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.timberchain.org
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.timecoin6.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.todaqfinance.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.todoblock.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.tokensoft.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.tomocredit.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.topl.co
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.tradefinancemarket.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.tradeline.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.trakti.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.translo.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.transonictransport.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.true-tickets.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.trustfractal.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.trustology.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.trustory.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.turbadium.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.tutellus.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.ubiquenet.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.uchange.cash
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.unik-name.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.unumid.org
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.urbytus.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.usebraintrust.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.utu.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.vairt.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.valid.network
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.valr.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.vaultoro.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.verismart.ai
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.veritabledata.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.vertrius.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.vesicash.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.vhk.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.viberate.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.vinx.wine
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.visualeo.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.volareo.live
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.vollar.org
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.volvero.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.vottun.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.vuulr.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.wagergames.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.wallepay.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.webblen.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.weeshing.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.welto.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.wemark.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.weturing.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.wimwisure.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.withcadence.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.xchaincoin.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.xenodes.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.xpense.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.xtech.ai
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.xyqkl.cn
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.yibenchain.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.yuhu.tech
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.yusur.tech
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.zettabyte.sg
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.zeus.exchange
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.zeux.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.zilliqa.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://www.zivter.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://xparent.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://yes-bit.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://youreit.gg
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://z.cash
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://zamna.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://zengold.org
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://zensports.com


exit
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://zerion.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://aarnav.io

java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://abacusfi.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://abe.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://account
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://acquicent.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://adhash.org
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://ahoolee.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://aion.theoan.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://aionsigma.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://air.life
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://aivia.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://alkemi.network
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://alluva.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://alphablock.org
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://alphabox.tech
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://alphawallet.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://althea.net
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://ambiafund.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://angel.co/hestia-1
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://angel.co/monadtech/jobs
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://anoloriya.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://anotemusic.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://anyl.site
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://apella.vote
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://app.tokensquare.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://arise.travel
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://arkane.network
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://aryia.ai
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://asicvault.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://aspireapp.co
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://assetnetwork.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://atlanticcrypto.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://atomicloans.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://attores.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://auracoins.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://axieinfinity.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://aximetria.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://base58.ch
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://basicblock.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://baypay.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://beatdapp.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://betterhealth.ai
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://bi.vip
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://bigcouch.co.uk
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://biilabs.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://bimchain.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://biochain.co.in
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://biock.health
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://bit2me.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://bitcv.one
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://bitooda.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://bitproof.io
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://bitshareslabs.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://bitsika.africa
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://bitz.network
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://bixiaobai.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://blinking.id
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://block-base.co
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://block2job.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://blockchain4africa.net
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://blockchaincybertech.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://blockchaintp.com
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG http://blockchainworx.com
