#!/bin/bash


JAR=/home/barb/Working/Git/Crawler4J/target/bbt-crawler4j-1.0.0-SNAPSHOT.jar
CRAWL_CONFIG=/home/barb/Working/Git/Scripts/config_JobBoards.txt
LOGGING_CONFIG=-Djava.util.logging.config.file=/home/barb/Working/Git/Scripts/logger.txt

java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG  "https://www.linkedin.com/jobs/search/?geoId=92000001&keywords=blockchain&location=Remote"
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG  "https://www.linkedin.com/jobs/search/?geoId=92000001&keywords=blockchain&location=Remote&start=25"

java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG  "https://www.linkedin.com/jobs/search/?geoId=90000084&keywords=blockchain&location=San%20Francisco%20Bay%20Area"
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG  "https://www.linkedin.com/jobs/search/?geoId=90000084&keywords=blockchain&location=San%20Francisco%20Bay%20Area&start=25"
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG  "https://www.linkedin.com/jobs/search/?geoId=90000084&keywords=blockchain&location=San%20Francisco%20Bay%20Area&start=50"
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG  "https://www.linkedin.com/jobs/search/?geoId=90000084&keywords=blockchain&location=San%20Francisco%20Bay%20Area&start=75"
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG  "https://www.linkedin.com/jobs/search/?geoId=90000084&keywords=blockchain&location=San%20Francisco%20Bay%20Area&start=100"
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG  "https://www.linkedin.com/jobs/search/?geoId=90000084&keywords=blockchain&location=San%20Francisco%20Bay%20Area&start=125"
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG  "https://www.linkedin.com/jobs/search/?geoId=90000084&keywords=blockchain&location=San%20Francisco%20Bay%20Area&start=150"
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG  "https://www.linkedin.com/jobs/search/?geoId=90000084&keywords=blockchain&location=San%20Francisco%20Bay%20Area&start=175"
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG  "https://www.linkedin.com/jobs/search/?geoId=90000084&keywords=blockchain&location=San%20Francisco%20Bay%20Area&start=200"
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG  "https://www.linkedin.com/jobs/search/?geoId=90000084&keywords=blockchain&location=San%20Francisco%20Bay%20Area&start=225"
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG  "https://www.linkedin.com/jobs/search/?geoId=90000084&keywords=blockchain&location=San%20Francisco%20Bay%20Area&start=250"
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG  "https://www.linkedin.com/jobs/search/?geoId=90000084&keywords=blockchain&location=San%20Francisco%20Bay%20Area&start=300"
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG  "https://www.linkedin.com/jobs/search/?geoId=90000084&keywords=blockchain&location=San%20Francisco%20Bay%20Area&start=325"
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG  "https://www.linkedin.com/jobs/search/?geoId=90000084&keywords=blockchain&location=San%20Francisco%20Bay%20Area&start=350"
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG  "https://www.linkedin.com/jobs/search/?geoId=90000084&keywords=blockchain&location=San%20Francisco%20Bay%20Area&start=375"
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG  "https://www.linkedin.com/jobs/search/?geoId=90000084&keywords=blockchain&location=San%20Francisco%20Bay%20Area&start=400"
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG  "https://www.linkedin.com/jobs/search/?geoId=90000084&keywords=blockchain&location=San%20Francisco%20Bay%20Area&start=425"
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG  "https://www.linkedin.com/jobs/search/?geoId=90000084&keywords=blockchain&location=San%20Francisco%20Bay%20Area&start=450"
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG  "https://www.linkedin.com/jobs/search/?geoId=90000084&keywords=blockchain&location=San%20Francisco%20Bay%20Area&start=475"
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG  "https://www.linkedin.com/jobs/search/?geoId=90000084&keywords=blockchain&location=San%20Francisco%20Bay%20Area&start=500"
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG  "https://www.linkedin.com/jobs/search/?geoId=90000084&keywords=blockchain&location=San%20Francisco%20Bay%20Area&start=525"
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG  "https://www.linkedin.com/jobs/search/?geoId=90000084&keywords=blockchain&location=San%20Francisco%20Bay%20Area&start=550"
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG  "https://www.linkedin.com/jobs/search/?geoId=90000084&keywords=blockchain&location=San%20Francisco%20Bay%20Area&start=600"
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG  "https://www.linkedin.com/jobs/search/?geoId=90000084&keywords=blockchain&location=San%20Francisco%20Bay%20Area&start=625"
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG  "https://www.linkedin.com/jobs/search/?geoId=90000084&keywords=blockchain&location=San%20Francisco%20Bay%20Area&start=700"
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG  "https://www.linkedin.com/jobs/search/?geoId=90000084&keywords=blockchain&location=San%20Francisco%20Bay%20Area&start=725"

java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG  "https://www.linkedin.com/jobs/search/?geoId=92000000&keywords=blockchain&location=Worldwide"
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG "https://www.linkedin.com/jobs/search/?geoId=92000000&keywords=blockchain&location=Worldde&start=0"
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG "https://www.linkedin.com/jobs/search/?geoId=92000000&keywords=blockchain&location=Worldde&start=20"
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG "https://www.linkedin.com/jobs/search/?geoId=92000000&keywords=blockchain&location=Worldde&start=40"
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG "https://www.linkedin.com/jobs/search/?geoId=92000000&keywords=blockchain&location=Worldde&start=60"
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG "https://www.linkedin.com/jobs/search/?geoId=92000000&keywords=blockchain&location=Worldde&start=80"
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG "https://www.linkedin.com/jobs/search/?geoId=92000000&keywords=blockchain&location=Worldde&start=100"
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG "https://www.linkedin.com/jobs/search/?geoId=92000000&keywords=blockchain&location=Worldde&start=120"
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG "https://www.linkedin.com/jobs/search/?geoId=92000000&keywords=blockchain&location=Worldde&start=140"
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG "https://www.linkedin.com/jobs/search/?geoId=92000000&keywords=blockchain&location=Worldde&start=160"
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG "https://www.linkedin.com/jobs/search/?geoId=92000000&keywords=blockchain&location=Worldde&start=180"
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG "https://www.linkedin.com/jobs/search/?geoId=92000000&keywords=blockchain&location=Worldde&start=200"
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG "https://www.linkedin.com/jobs/search/?geoId=92000000&keywords=blockchain&location=Worldde&start=220"
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG "https://www.linkedin.com/jobs/search/?geoId=92000000&keywords=blockchain&location=Worldde&start=240"
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG "https://www.linkedin.com/jobs/search/?geoId=92000000&keywords=blockchain&location=Worldde&start=260"
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG "https://www.linkedin.com/jobs/search/?geoId=92000000&keywords=blockchain&location=Worldde&start=280"
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG "https://www.linkedin.com/jobs/search/?geoId=92000000&keywords=blockchain&location=Worldde&start=300"
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG "https://www.linkedin.com/jobs/search/?geoId=92000000&keywords=blockchain&location=Worldde&start=320"
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG "https://www.linkedin.com/jobs/search/?geoId=92000000&keywords=blockchain&location=Worldde&start=340"
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG "https://www.linkedin.com/jobs/search/?geoId=92000000&keywords=blockchain&location=Worldde&start=360"
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG "https://www.linkedin.com/jobs/search/?geoId=92000000&keywords=blockchain&location=Worldde&start=380"
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG "https://www.linkedin.com/jobs/search/?geoId=92000000&keywords=blockchain&location=Worldde&start=400"
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG "https://www.linkedin.com/jobs/search/?geoId=92000000&keywords=blockchain&location=Worldde&start=420"
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG "https://www.linkedin.com/jobs/search/?geoId=92000000&keywords=blockchain&location=Worldde&start=440"
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG "https://www.linkedin.com/jobs/search/?geoId=92000000&keywords=blockchain&location=Worldde&start=460"
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG "https://www.linkedin.com/jobs/search/?geoId=92000000&keywords=blockchain&location=Worldde&start=480"
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG "https://www.linkedin.com/jobs/search/?geoId=92000000&keywords=blockchain&location=Worldde&start=500"
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG "https://www.linkedin.com/jobs/search/?geoId=92000000&keywords=blockchain&location=Worldde&start=520"
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG "https://www.linkedin.com/jobs/search/?geoId=92000000&keywords=blockchain&location=Worldde&start=540"
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG "https://www.linkedin.com/jobs/search/?geoId=92000000&keywords=blockchain&location=Worldde&start=560"
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG "https://www.linkedin.com/jobs/search/?geoId=92000000&keywords=blockchain&location=Worldde&start=580"
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG "https://www.linkedin.com/jobs/search/?geoId=92000000&keywords=blockchain&location=Worldde&start=600"
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG "https://www.linkedin.com/jobs/search/?geoId=92000000&keywords=blockchain&location=Worldde&start=620"
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG "https://www.linkedin.com/jobs/search/?geoId=92000000&keywords=blockchain&location=Worldde&start=640"
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG "https://www.linkedin.com/jobs/search/?geoId=92000000&keywords=blockchain&location=Worldde&start=660"
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG "https://www.linkedin.com/jobs/search/?geoId=92000000&keywords=blockchain&location=Worldde&start=680"
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG "https://www.linkedin.com/jobs/search/?geoId=92000000&keywords=blockchain&location=Worldde&start=700"
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG "https://www.linkedin.com/jobs/search/?geoId=92000000&keywords=blockchain&location=Worldde&start=720"
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG "https://www.linkedin.com/jobs/search/?geoId=92000000&keywords=blockchain&location=Worldde&start=740"
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG "https://www.linkedin.com/jobs/search/?geoId=92000000&keywords=blockchain&location=Worldde&start=760"
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG "https://www.linkedin.com/jobs/search/?geoId=92000000&keywords=blockchain&location=Worldde&start=780"
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG "https://www.linkedin.com/jobs/search/?geoId=92000000&keywords=blockchain&location=Worldde&start=800"
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG "https://www.linkedin.com/jobs/search/?geoId=92000000&keywords=blockchain&location=Worldde&start=820"
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG "https://www.linkedin.com/jobs/search/?geoId=92000000&keywords=blockchain&location=Worldde&start=840"
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG "https://www.linkedin.com/jobs/search/?geoId=92000000&keywords=blockchain&location=Worldde&start=860"
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG "https://www.linkedin.com/jobs/search/?geoId=92000000&keywords=blockchain&location=Worldde&start=880"
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG "https://www.linkedin.com/jobs/search/?geoId=92000000&keywords=blockchain&location=Worldde&start=900"
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG "https://www.linkedin.com/jobs/search/?geoId=92000000&keywords=blockchain&location=Worldde&start=920"
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG "https://www.linkedin.com/jobs/search/?geoId=92000000&keywords=blockchain&location=Worldde&start=940"
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG "https://www.linkedin.com/jobs/search/?geoId=92000000&keywords=blockchain&location=Worldde&start=960"
java -jar $LOGGING_CONFIG $JAR $CRAWL_CONFIG "https://www.linkedin.com/jobs/search/?geoId=92000000&keywords=blockchain&location=Worldde&start=980"
